const CACHE_NAME = 'marrow-planner-pwa-v187';

// DATA_FILES_START — auto-generated by scripts/bump-version.js from STUDY_SOURCES.dataFile
// Do not edit this block manually; add new sources to js/core/constants.js instead.
const DATA_FILES = [
  './data.js',
  './data_marrow_6_5.js'
];
// DATA_FILES_END

const ASSETS = [
  './',
  './index.html',
  './style.css',
  './app.js',
  './firebase.js',
  './js/core/namespace.js',
  './js/core/constants.js',
  './js/core/state-store.js',
  './js/core/source-data.js',
  './js/core/metrics.js',
  './js/core/subjects.js',
  './js/core/logo.js',
  './js/core/sync.js',
  './js/features/toast.js',
  './js/features/theme.js',
  './js/features/search.js',
  './js/features/sync.js',
  './js/features/onboarding.js',
  './js/features/study-plan-config.js',
  './js/features/source-settings.js',
  './js/features/charts.js',
  './js/features/views/dashboard.js',
  './js/features/views/curriculum.js',
  './js/features/views/subject-detail.js',
  './js/features/views/analytics.js',
  './js/features/views/profile.js',
  './icon.svg',
  './manifest.json',
  './offline.html',
  './privacy.html',
  './assets/icon-192.png',
  './assets/icon-512.png',
  ...DATA_FILES
];

// Firebase SDKs (cross-origin) - cached on first load
const FIREBASE_SDKS = [
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore-compat.js'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS).catch(e => console.log('Cache add failed', e));
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  const cacheKey = url.origin + url.pathname;
  const isNavigate = request.mode === 'navigate';
  const isFont = url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com';
  const isFirebaseSDK = FIREBASE_SDKS.some(sdk => request.url.startsWith(sdk));

  // Google Fonts (CSS + woff2): network-first, cache on success, cache offline.
  // Never falls back to offline.html — an HTML document must not be served
  // as a font (that's what turned Material Symbols into raw ligature text
  // like "local_fire_department" when offline).
  if (isFont) {
    event.respondWith(
      caches.open(CACHE_NAME).then((cache) => {
        return fetch(request).then((networkResponse) => {
          if (networkResponse && networkResponse.ok) {
            cache.put(cacheKey, networkResponse.clone());
          }
          return networkResponse;
        }).catch(() => cache.match(cacheKey));
      })
    );
    return;
  }

  // Firebase SDKs: cache on first load, serve from cache when offline
  if (isFirebaseSDK) {
    event.respondWith(
      caches.open(CACHE_NAME).then((cache) => {
        return cache.match(request).then((cached) => {
          return cached || fetch(request).then((networkResponse) => {
            cache.put(request, networkResponse.clone());
            return networkResponse;
          });
        });
      })
    );
    return;
  }

  // Navigations: network-first, offline falls back to the cached app shell
  // (full offline app), with offline.html as a last resort. The query string
  // is stripped from the cache key so ?v= cache-busting never misses.
  if (isNavigate) {
    event.respondWith(
      fetch(request)
        .then((networkResponse) => {
          const copy = networkResponse.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(cacheKey, copy));
          return networkResponse;
        })
        .catch(() =>
          caches.match('./index.html').then((cached) => cached || caches.match('./offline.html'))
        )
    );
    return;
  }

  // Same-origin assets (scripts, styles, data, icons): network-first, cache
  // on success, cache offline. No offline.html fallback for non-navigations.
  event.respondWith(
    fetch(request)
      .then((networkResponse) => {
        const copy = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(cacheKey, copy));
        return networkResponse;
      })
      .catch(() => caches.match(cacheKey))
  );
});
