const CACHE_NAME = 'marrow-planner-pwa-v8';

// DATA_FILES_START — auto-generated by scripts/bump-version.js from STUDY_SOURCES.dataFile
// Do not edit this block manually; add new sources to js/core/constants.js instead.
const DATA_FILES = [
  './data.js',
  './data_marrow_6_5.js'
];
// DATA_FILES_END

const ASSETS = [
  './',
  './index.html',
  './style.css',
  './app.js',
  './firebase.js',
  './js/core/namespace.js',
  './js/core/constants.js',
  './js/core/state-store.js',
  './js/core/source-data.js',
  './js/core/metrics.js',
  './js/core/subjects.js',
  './js/core/logo.js',
  './js/features/toast.js',
  './js/features/theme.js',
  './js/features/search.js',
  './js/features/sync.js',
  './icon.svg',
  './manifest.json',
  './offline.html',
  './assets/icon-192.png',
  './assets/icon-512.png',
  ...DATA_FILES
];

// Firebase SDKs (cross-origin) - cached on first load
const FIREBASE_SDKS = [
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore-compat.js'
];

const CURRICULUM_CACHE = 'marrow-curriculum-v1';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS).catch(e => console.log('Cache add failed', e));
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME && k !== CURRICULUM_CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  const cacheKey = url.origin + url.pathname;
  const isFirebaseSDK = FIREBASE_SDKS.some(sdk => request.url.startsWith(sdk));

  if (url.pathname.includes('curriculum') || url.pathname.endsWith('/')) {
    event.respondWith(
      caches.open(CURRICULUM_CACHE).then((cache) => {
        return fetch(request).then((networkResponse) => {
          cache.put(cacheKey, networkResponse.clone());
          return networkResponse;
        }).catch(() => cache.match(cacheKey));
      })
    );
    return;
  }

  // Firebase SDKs: cache on first load, serve from cache when offline
  if (isFirebaseSDK) {
    event.respondWith(
      caches.open(CACHE_NAME).then((cache) => {
        return cache.match(request).then((cached) => {
          return cached || fetch(request).then((networkResponse) => {
            cache.put(request, networkResponse.clone());
            return networkResponse;
          });
        });
      })
    );
    return;
  }

  // Same-origin: network-first with offline fallback to offline.html
  event.respondWith(
    fetch(request)
      .then((networkResponse) => {
        const copy = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(cacheKey, copy));
        return networkResponse;
      })
      .catch(() => caches.match(cacheKey).then((cached) => {
        if (!cached && request.mode === 'navigate') {
          return caches.match('./offline.html');
        }
        return cached || caches.match('./offline.html');
      }))
  );
});
