const CACHE_NAME = 'marrow-planner-pwa-v229';

// DATA_FILES_START — auto-generated by scripts/bump-version.js from STUDY_SOURCES.dataFile
// Do not edit this block manually; add new sources to js/core/constants.js instead.
const DATA_FILES = [
  './data.js',
  './data_marrow_6_5.js'
];
// DATA_FILES_END

const FIREBASE_SDK = [
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore-compat.js',
  'https://www.gstatic.com/firebasejs/10.8.0/firebase-analytics-compat.js'
];

const ASSETS = [
  './',
  './index.html',
  './style.css',
  './app.js',
  './js/core/namespace.js',
  './js/core/constants.js',
  './js/core/icons.js',
  './js/core/state-store.js',
  './js/core/source-data.js',
  './js/core/metrics.js',
  './js/core/subjects.js',
  './js/core/logo.js',
  './js/features/toast.js',
  './js/features/theme.js',
  './js/features/search.js',
  './js/features/onboarding.js',
  './js/features/backup.js',
  './js/features/pwa-install.js',
  './js/features/study-plan-config.js',
  './js/features/source-settings.js',
  './js/features/charts.js',
  './js/features/views/dashboard.js',
  './js/features/views/curriculum.js',
  './js/features/views/subject-detail.js',
  './js/features/views/analytics.js',
  './js/features/views/profile.js',
  './icon.svg',
  './manifest.json',
  './offline.html',
  './privacy.html',
  './terms.html',
  './assets/icon-192.png',
  './assets/icon-512.png',
  ...DATA_FILES
];

// Cache key: origin + pathname (query stripped) - matches the runtime
// fetch-handler keys so precached entries are found by cache.match.
function cacheKeyFor(url) {
  return url.origin + url.pathname;
}

// Resolve on success, or after `ms` - a slow asset must never hang install.
function withTimeout(promise, ms) {
  return Promise.race([promise, new Promise((resolve) => setTimeout(resolve, ms))]);
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      // Same-origin shell + data files.
      await cache.addAll(ASSETS).catch(e => console.log('Cache add failed', e));
      // Cross-origin Firebase SDKs — addAll rejects on opaque responses,
      // so cache each individually.
      for (const url of FIREBASE_SDK) {
        try { await withTimeout(cache.add(url), 8000); } catch (_) { /* non-critical */ }
      }
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  const cacheKey = url.origin + url.pathname;
  const isNavigate = request.mode === 'navigate';

  // Navigations: network-first, offline falls back to the cached app shell
  // (full offline app), with offline.html as a last resort. The query string
  // is stripped from the cache key so ?v= cache-busting never misses.
  if (isNavigate) {
    event.respondWith(
      fetch(request)
        .then((networkResponse) => {
          const copy = networkResponse.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(cacheKey, copy));
          return networkResponse;
        })
        .catch(() =>
          caches.match('./index.html').then((cached) => cached || caches.match('./offline.html'))
        )
    );
    return;
  }

  // Same-origin assets (scripts, styles, data, icons): network-first, cache
  // on success, cache offline. No offline.html fallback for non-navigations.
  event.respondWith(
    fetch(request)
      .then((networkResponse) => {
        const copy = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(cacheKey, copy));
        return networkResponse;
      })
      .catch(() => caches.match(cacheKey))
  );
});
